"""add api keys and query run audit

Revision ID: 30482d58497e
Revises: b4c68ade9650
Create Date: 2026-09-03 19:03:15.992135

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# query_runs is ordinary tenant data and gets the usual policy.
#
# api_keys deliberately does NOT. Verifying a key means reading this table, and
# the tenant a policy would filter on is the thing the key is being read to
# discover — the policy would have to be satisfied before it could be evaluated.
# Same chicken-and-egg as `tenants`. Safe because only SHA-256 digests of
# 32-byte random secrets are stored: read access grants no impersonation.
RLS_TABLES = ("query_runs",)
RLS_POLICY = "tenant_isolation"
RLS_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
# Alembic renders pgvector column types fully qualified without importing them.
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = '30482d58497e'
down_revision: str | None = 'b4c68ade9650'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(key_hash) = 64', name=op.f('ck_api_keys_key_hash_is_sha256')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_api_keys_name_present')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_api_keys_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_api_keys_id_tenant_id')
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('query_runs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('semantic_model_version_id', sa.Uuid(), nullable=True),
    sa.Column('api_key_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('compiled', 'executed', 'failed', name='run_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('intent', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('compiled_sql', sa.Text(), nullable=True),
    sa.Column('parameter_count', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('problems', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'tenant_id'], ['workspaces.id', 'workspaces.tenant_id'], name='fk_query_runs_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_runs')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_query_runs_id_tenant_id')
    )
    op.create_index(op.f('ix_query_runs_api_key_id'), 'query_runs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_query_runs_semantic_model_version_id'), 'query_runs', ['semantic_model_version_id'], unique=False)
    op.create_index(op.f('ix_query_runs_tenant_id'), 'query_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_query_runs_workspace_id'), 'query_runs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {RLS_POLICY} ON {table} "
            f"USING ({RLS_PREDICATE}) "
            f"WITH CHECK ({RLS_PREDICATE})"
        )


def downgrade() -> None:
    for table in reversed(RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS {RLS_POLICY} ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_runs_workspace_id'), table_name='query_runs')
    op.drop_index(op.f('ix_query_runs_tenant_id'), table_name='query_runs')
    op.drop_index(op.f('ix_query_runs_semantic_model_version_id'), table_name='query_runs')
    op.drop_index(op.f('ix_query_runs_api_key_id'), table_name='query_runs')
    op.drop_table('query_runs')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
