"""add data sources and bind versions to them

Revision ID: 30be7d5f0513
Revises: 3e31df0b7170
Create Date: 2026-09-02 17:40:59.306455

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

RLS_TABLES = ("data_sources",)
RLS_POLICY = "tenant_isolation"
RLS_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"

# The Step 16 CHECK constraints were named with the table prefix already in
# them, which the ck_%(table_name)s_%(constraint_name)s convention then doubled.
CHECK_RENAMES = (
    ("entities", "ck_entities_ck_entities_name_ident", "ck_entities_name_ident"),
    (
        "entities",
        "ck_entities_ck_entities_primary_key_ident",
        "ck_entities_primary_key_ident",
    ),
    (
        "entities",
        "ck_entities_ck_entities_source_schema_ident",
        "ck_entities_source_schema_ident",
    ),
    (
        "entities",
        "ck_entities_ck_entities_source_table_ident",
        "ck_entities_source_table_ident",
    ),
)


revision: str = '30be7d5f0513'
down_revision: str | None = '3e31df0b7170'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dialect', sa.Enum('postgresql', name='data_source_dialect', native_enum=False, create_constraint=True, length=32), server_default='postgresql', nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.SmallInteger(), nullable=False),
    sa.Column('default_schema', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_schema ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_data_sources_schema_ident')),
    sa.CheckConstraint('length(host) > 0', name=op.f('ck_data_sources_host_present')),
    sa.CheckConstraint('port > 0 AND port <= 65535', name=op.f('ck_data_sources_port_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'tenant_id'], ['workspaces.id', 'workspaces.tenant_id'], name='fk_data_sources_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_data_sources_id_tenant_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_data_sources_workspace_id_name')
    )
    op.create_index(op.f('ix_data_sources_tenant_id'), 'data_sources', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_data_sources_workspace_id'), 'data_sources', ['workspace_id'], unique=False)
    op.add_column('semantic_model_versions', sa.Column('data_source_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_semantic_model_versions_data_source_id'), 'semantic_model_versions', ['data_source_id'], unique=False)
    op.create_foreign_key('fk_semantic_model_versions_data_source_id', 'semantic_model_versions', 'data_sources', ['data_source_id', 'tenant_id'], ['id', 'tenant_id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    for table, old_name, new_name in CHECK_RENAMES:
        op.execute(f"ALTER TABLE {table} RENAME CONSTRAINT {old_name} TO {new_name}")

    # Alembic does not autogenerate CHECK constraints; this one is the invariant
    # that a published version must name the data source it compiles against.
    op.create_check_constraint(
        "published_has_source",
        "semantic_model_versions",
        "status <> 'published' OR data_source_id IS NOT NULL",
    )

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {RLS_POLICY} ON {table} "
            f"USING ({RLS_PREDICATE}) "
            f"WITH CHECK ({RLS_PREDICATE})"
        )


def downgrade() -> None:
    for table in reversed(RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS {RLS_POLICY} ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # Bare name: drop_constraint applies the ck_ naming convention.
    op.drop_constraint("published_has_source", "semantic_model_versions", type_="check")

    for table, old_name, new_name in CHECK_RENAMES:
        op.execute(f"ALTER TABLE {table} RENAME CONSTRAINT {new_name} TO {old_name}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_semantic_model_versions_data_source_id', 'semantic_model_versions', type_='foreignkey')
    op.drop_index(op.f('ix_semantic_model_versions_data_source_id'), table_name='semantic_model_versions')
    op.drop_column('semantic_model_versions', 'data_source_id')
    op.drop_index(op.f('ix_data_sources_workspace_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_tenant_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
