"""add entities

Revision ID: 3e31df0b7170
Revises: bbc8ba79661c
Create Date: 2026-09-02 17:18:58.908277

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

RLS_TABLES = ("entities",)
RLS_POLICY = "tenant_isolation"
RLS_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"

# The composite-FK naming scheme dropped the parent table from the name: keeping
# it pushed `business_rules` -> `semantic_model_versions` to 67 characters, past
# Postgres's 63-character identifier limit. Renaming the two constraints already
# in the database so every table follows one scheme.
RENAMES = (
    (
        "semantic_models",
        "fk_semantic_models_workspace_id_workspaces",
        "fk_semantic_models_workspace_id",
    ),
    (
        "semantic_model_versions",
        "fk_semantic_model_versions_semantic_model_id_semantic_models",
        "fk_semantic_model_versions_semantic_model_id",
    ),
)


revision: str = '3e31df0b7170'
down_revision: str | None = 'bbc8ba79661c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('semantic_model_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_schema', sa.String(length=255), nullable=False),
    sa.Column('source_table', sa.String(length=255), nullable=False),
    sa.Column('primary_key', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('fact', 'dimension', name='entity_kind', native_enum=False, create_constraint=True, length=32), server_default='dimension', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_entities_ck_entities_name_ident')),
    sa.CheckConstraint("primary_key ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_entities_ck_entities_primary_key_ident')),
    sa.CheckConstraint("source_schema ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_entities_ck_entities_source_schema_ident')),
    sa.CheckConstraint("source_table ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_entities_ck_entities_source_table_ident')),
    sa.ForeignKeyConstraint(['semantic_model_version_id', 'tenant_id'], ['semantic_model_versions.id', 'semantic_model_versions.tenant_id'], name='fk_entities_semantic_model_version_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_entities_id_tenant_id'),
    sa.UniqueConstraint('semantic_model_version_id', 'name', name='uq_entities_version_id_name')
    )
    op.create_index(op.f('ix_entities_semantic_model_version_id'), 'entities', ['semantic_model_version_id'], unique=False)
    op.create_index(op.f('ix_entities_tenant_id'), 'entities', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table, old_name, new_name in RENAMES:
        op.execute(f"ALTER TABLE {table} RENAME CONSTRAINT {old_name} TO {new_name}")

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {RLS_POLICY} ON {table} "
            f"USING ({RLS_PREDICATE}) "
            f"WITH CHECK ({RLS_PREDICATE})"
        )


def downgrade() -> None:
    for table in reversed(RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS {RLS_POLICY} ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    for table, old_name, new_name in RENAMES:
        op.execute(f"ALTER TABLE {table} RENAME CONSTRAINT {new_name} TO {old_name}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_tenant_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_semantic_model_version_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
