"""add relationships and join keys

Revision ID: 4dce57280e82
Revises: 672080b0a824
Create Date: 2026-09-02 18:48:26.266815

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

RLS_TABLES = ("relationships", "relationship_join_keys")
RLS_POLICY = "tenant_isolation"
RLS_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"


revision: str = '4dce57280e82'
down_revision: str | None = '672080b0a824'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('semantic_model_version_id', sa.Uuid(), nullable=False),
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('join_type', sa.Enum('inner', 'left', name='join_type', native_enum=False, create_constraint=True, length=32), server_default='inner', nullable=False),
    sa.Column('cardinality', sa.Enum('many_to_one', 'one_to_many', 'one_to_one', name='cardinality', native_enum=False, create_constraint=True, length=32), server_default='many_to_one', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_relationships_name_ident')),
    sa.CheckConstraint('from_entity_id <> to_entity_id', name=op.f('ck_relationships_no_self_join')),
    sa.ForeignKeyConstraint(['from_entity_id', 'semantic_model_version_id', 'tenant_id'], ['entities.id', 'entities.semantic_model_version_id', 'entities.tenant_id'], name='fk_relationships_from_entity_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id', 'semantic_model_version_id', 'tenant_id'], ['entities.id', 'entities.semantic_model_version_id', 'entities.tenant_id'], name='fk_relationships_to_entity_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_relationships_id_tenant_id'),
    sa.UniqueConstraint('semantic_model_version_id', 'from_entity_id', 'to_entity_id', name='uq_relationships_version_from_to'),
    sa.UniqueConstraint('semantic_model_version_id', 'name', name='uq_relationships_version_id_name')
    )
    op.create_index(op.f('ix_relationships_from_entity_id'), 'relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_semantic_model_version_id'), 'relationships', ['semantic_model_version_id'], unique=False)
    op.create_index(op.f('ix_relationships_tenant_id'), 'relationships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_relationships_to_entity_id'), 'relationships', ['to_entity_id'], unique=False)
    op.create_table('relationship_join_keys',
    sa.Column('relationship_id', sa.Uuid(), nullable=False),
    sa.Column('from_column', sa.String(length=255), nullable=False),
    sa.Column('to_column', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("from_column ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_relationship_join_keys_from_column_ident')),
    sa.CheckConstraint("to_column ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_relationship_join_keys_to_column_ident')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_relationship_join_keys_ordinal_non_negative')),
    sa.ForeignKeyConstraint(['relationship_id', 'tenant_id'], ['relationships.id', 'relationships.tenant_id'], name='fk_relationship_join_keys_relationship_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship_join_keys')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_relationship_join_keys_id_tenant_id'),
    sa.UniqueConstraint('relationship_id', 'ordinal', name='uq_relationship_join_keys_relationship_ordinal')
    )
    op.create_index(op.f('ix_relationship_join_keys_relationship_id'), 'relationship_join_keys', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_relationship_join_keys_tenant_id'), 'relationship_join_keys', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {RLS_POLICY} ON {table} "
            f"USING ({RLS_PREDICATE}) "
            f"WITH CHECK ({RLS_PREDICATE})"
        )


def downgrade() -> None:
    for table in reversed(RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS {RLS_POLICY} ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_join_keys_tenant_id'), table_name='relationship_join_keys')
    op.drop_index(op.f('ix_relationship_join_keys_relationship_id'), table_name='relationship_join_keys')
    op.drop_table('relationship_join_keys')
    op.drop_index(op.f('ix_relationships_to_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_tenant_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_semantic_model_version_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_entity_id'), table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
