"""add measures metrics and metric references

Revision ID: 672080b0a824
Revises: 692198b13b72
Create Date: 2026-09-02 18:40:13.341394

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

RLS_TABLES = ("metrics", "measures", "metric_references")
RLS_POLICY = "tenant_isolation"
RLS_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"


revision: str = '672080b0a824'
down_revision: str | None = '692198b13b72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-corrected: autogenerate emitted this unique constraint after the
    # measures table that references it, which Postgres rejects.
    op.create_unique_constraint('id_version_tenant', 'entities', ['id', 'semantic_model_version_id', 'tenant_id'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('semantic_model_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expression', sa.String(length=1000), nullable=False),
    sa.Column('format', sa.Enum('number', 'currency', 'percent', name='metric_format', native_enum=False, create_constraint=True, length=32), server_default='number', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("expression ~ '^[A-Za-z0-9_ ${}+*/().-]+$' AND expression NOT LIKE '%%--%%'", name=op.f('ck_metrics_expression_charset')),
    sa.CheckConstraint("name ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_metrics_name_ident')),
    sa.ForeignKeyConstraint(['semantic_model_version_id', 'tenant_id'], ['semantic_model_versions.id', 'semantic_model_versions.tenant_id'], name='fk_metrics_semantic_model_version_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_metrics_id_tenant_id'),
    sa.UniqueConstraint('semantic_model_version_id', 'name', name='uq_metrics_version_id_name')
    )
    op.create_index(op.f('ix_metrics_semantic_model_version_id'), 'metrics', ['semantic_model_version_id'], unique=False)
    op.create_index(op.f('ix_metrics_tenant_id'), 'metrics', ['tenant_id'], unique=False)
    op.create_table('measures',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('semantic_model_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aggregation', sa.Enum('sum', 'count', 'count_distinct', 'avg', 'min', 'max', name='aggregation', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('expression', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("expression ~ '^[A-Za-z0-9_ +*/().-]+$' AND expression NOT LIKE '%%--%%'", name=op.f('ck_measures_expression_charset')),
    sa.CheckConstraint("name ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_measures_name_ident')),
    sa.ForeignKeyConstraint(['entity_id', 'semantic_model_version_id', 'tenant_id'], ['entities.id', 'entities.semantic_model_version_id', 'entities.tenant_id'], name='fk_measures_entity_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measures')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_measures_id_tenant_id'),
    sa.UniqueConstraint('semantic_model_version_id', 'name', name='uq_measures_version_id_name')
    )
    op.create_index(op.f('ix_measures_entity_id'), 'measures', ['entity_id'], unique=False)
    op.create_index(op.f('ix_measures_semantic_model_version_id'), 'measures', ['semantic_model_version_id'], unique=False)
    op.create_index(op.f('ix_measures_tenant_id'), 'measures', ['tenant_id'], unique=False)
    op.create_table('metric_references',
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('ref_measure_id', sa.Uuid(), nullable=True),
    sa.Column('ref_metric_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(ref_measure_id IS NULL) <> (ref_metric_id IS NULL)', name=op.f('ck_metric_references_exactly_one_target')),
    sa.CheckConstraint('ref_metric_id IS NULL OR ref_metric_id <> metric_id', name=op.f('ck_metric_references_no_self_reference')),
    sa.ForeignKeyConstraint(['metric_id', 'tenant_id'], ['metrics.id', 'metrics.tenant_id'], name='fk_metric_references_metric_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_measure_id', 'tenant_id'], ['measures.id', 'measures.tenant_id'], name='fk_metric_references_ref_measure_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_metric_id', 'tenant_id'], ['metrics.id', 'metrics.tenant_id'], name='fk_metric_references_ref_metric_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_references'))
    )
    op.create_index(op.f('ix_metric_references_metric_id'), 'metric_references', ['metric_id'], unique=False)
    op.create_index(op.f('ix_metric_references_ref_measure_id'), 'metric_references', ['ref_measure_id'], unique=False)
    op.create_index(op.f('ix_metric_references_ref_metric_id'), 'metric_references', ['ref_metric_id'], unique=False)
    op.create_index(op.f('ix_metric_references_tenant_id'), 'metric_references', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {RLS_POLICY} ON {table} "
            f"USING ({RLS_PREDICATE}) "
            f"WITH CHECK ({RLS_PREDICATE})"
        )


def downgrade() -> None:
    for table in reversed(RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS {RLS_POLICY} ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_references_tenant_id'), table_name='metric_references')
    op.drop_index(op.f('ix_metric_references_ref_metric_id'), table_name='metric_references')
    op.drop_index(op.f('ix_metric_references_ref_measure_id'), table_name='metric_references')
    op.drop_index(op.f('ix_metric_references_metric_id'), table_name='metric_references')
    op.drop_table('metric_references')
    op.drop_index(op.f('ix_measures_tenant_id'), table_name='measures')
    op.drop_index(op.f('ix_measures_semantic_model_version_id'), table_name='measures')
    op.drop_index(op.f('ix_measures_entity_id'), table_name='measures')
    op.drop_table('measures')
    op.drop_index(op.f('ix_metrics_tenant_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_semantic_model_version_id'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
    op.drop_constraint('id_version_tenant', 'entities', type_='unique')
