"""add dimensions

Revision ID: 692198b13b72
Revises: 30be7d5f0513
Create Date: 2026-09-02 18:35:07.227887

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

RLS_TABLES = ("dimensions",)
RLS_POLICY = "tenant_isolation"
RLS_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"


revision: str = '692198b13b72'
down_revision: str | None = '30be7d5f0513'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimensions',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expression', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.Enum('string', 'number', 'boolean', 'date', 'timestamp', name='dimension_data_type', native_enum=False, create_constraint=True, length=32), server_default='string', nullable=False),
    sa.Column('granularity', sa.Enum('day', 'week', 'month', 'quarter', 'year', name='time_granularity', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("expression ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_dimensions_expression_ident')),
    sa.CheckConstraint("granularity IS NULL OR data_type IN ('date', 'timestamp')", name=op.f('ck_dimensions_granularity_requires_time_type')),
    sa.CheckConstraint("name ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_dimensions_name_ident')),
    sa.ForeignKeyConstraint(['entity_id', 'tenant_id'], ['entities.id', 'entities.tenant_id'], name='fk_dimensions_entity_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dimensions')),
    sa.UniqueConstraint('entity_id', 'name', name='uq_dimensions_entity_id_name'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_dimensions_id_tenant_id')
    )
    op.create_index(op.f('ix_dimensions_entity_id'), 'dimensions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_dimensions_tenant_id'), 'dimensions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {RLS_POLICY} ON {table} "
            f"USING ({RLS_PREDICATE}) "
            f"WITH CHECK ({RLS_PREDICATE})"
        )


def downgrade() -> None:
    for table in reversed(RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS {RLS_POLICY} ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dimensions_tenant_id'), table_name='dimensions')
    op.drop_index(op.f('ix_dimensions_entity_id'), table_name='dimensions')
    op.drop_table('dimensions')
    # ### end Alembic commands ###
