"""add business rules glossary and synonyms

Revision ID: 9d1c87c2f6cc
Revises: 4dce57280e82
Create Date: 2026-09-02 18:57:30.749799

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

RLS_TABLES = ("glossary_terms", "business_rules", "synonyms")
RLS_POLICY = "tenant_isolation"
RLS_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
from sqlalchemy.dialects import postgresql

revision: str = '9d1c87c2f6cc'
down_revision: str | None = '4dce57280e82'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_terms',
    sa.Column('semantic_model_version_id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(definition)) > 0', name=op.f('ck_glossary_terms_definition_present')),
    sa.CheckConstraint('length(trim(term)) > 0', name=op.f('ck_glossary_terms_term_present')),
    sa.ForeignKeyConstraint(['semantic_model_version_id', 'tenant_id'], ['semantic_model_versions.id', 'semantic_model_versions.tenant_id'], name='fk_glossary_terms_semantic_model_version_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_terms')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_glossary_terms_id_tenant_id'),
    sa.UniqueConstraint('semantic_model_version_id', 'term', name='uq_glossary_terms_version_id_term')
    )
    op.create_index(op.f('ix_glossary_terms_semantic_model_version_id'), 'glossary_terms', ['semantic_model_version_id'], unique=False)
    op.create_index(op.f('ix_glossary_terms_tenant_id'), 'glossary_terms', ['tenant_id'], unique=False)
    op.create_table('business_rules',
    sa.Column('semantic_model_version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.Enum('eq', 'ne', 'lt', 'lte', 'gt', 'gte', 'in', 'not_in', 'is_null', 'is_not_null', name='filter_operator', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(operator IN ('is_null', 'is_not_null')) = (value IS NULL OR jsonb_typeof(value) = 'null')", name=op.f('ck_business_rules_value_matches_operator')),
    sa.CheckConstraint("column_name ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_business_rules_column_ident')),
    sa.CheckConstraint("name ~ '^[A-Za-z_][A-Za-z0-9_]*$'", name=op.f('ck_business_rules_name_ident')),
    sa.ForeignKeyConstraint(['entity_id', 'semantic_model_version_id', 'tenant_id'], ['entities.id', 'entities.semantic_model_version_id', 'entities.tenant_id'], name='fk_business_rules_entity_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_rules')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_business_rules_id_tenant_id'),
    sa.UniqueConstraint('semantic_model_version_id', 'name', name='uq_business_rules_version_id_name')
    )
    op.create_index(op.f('ix_business_rules_entity_id'), 'business_rules', ['entity_id'], unique=False)
    op.create_index(op.f('ix_business_rules_semantic_model_version_id'), 'business_rules', ['semantic_model_version_id'], unique=False)
    op.create_index(op.f('ix_business_rules_tenant_id'), 'business_rules', ['tenant_id'], unique=False)
    op.create_table('synonyms',
    sa.Column('semantic_model_version_id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('dimension_id', sa.Uuid(), nullable=True),
    sa.Column('metric_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(entity_id IS NOT NULL)::int + (dimension_id IS NOT NULL)::int + (metric_id IS NOT NULL)::int = 1', name=op.f('ck_synonyms_exactly_one_target')),
    sa.CheckConstraint('length(trim(term)) > 0', name=op.f('ck_synonyms_term_present')),
    sa.ForeignKeyConstraint(['dimension_id', 'tenant_id'], ['dimensions.id', 'dimensions.tenant_id'], name='fk_synonyms_dimension_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id', 'tenant_id'], ['entities.id', 'entities.tenant_id'], name='fk_synonyms_entity_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id', 'tenant_id'], ['metrics.id', 'metrics.tenant_id'], name='fk_synonyms_metric_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semantic_model_version_id', 'tenant_id'], ['semantic_model_versions.id', 'semantic_model_versions.tenant_id'], name='fk_synonyms_semantic_model_version_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_synonyms')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_synonyms_id_tenant_id'),
    sa.UniqueConstraint('semantic_model_version_id', 'term', name='uq_synonyms_version_id_term')
    )
    op.create_index(op.f('ix_synonyms_dimension_id'), 'synonyms', ['dimension_id'], unique=False)
    op.create_index(op.f('ix_synonyms_entity_id'), 'synonyms', ['entity_id'], unique=False)
    op.create_index(op.f('ix_synonyms_metric_id'), 'synonyms', ['metric_id'], unique=False)
    op.create_index(op.f('ix_synonyms_semantic_model_version_id'), 'synonyms', ['semantic_model_version_id'], unique=False)
    op.create_index(op.f('ix_synonyms_tenant_id'), 'synonyms', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {RLS_POLICY} ON {table} "
            f"USING ({RLS_PREDICATE}) "
            f"WITH CHECK ({RLS_PREDICATE})"
        )


def downgrade() -> None:
    for table in reversed(RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS {RLS_POLICY} ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_synonyms_tenant_id'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_semantic_model_version_id'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_metric_id'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_entity_id'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_dimension_id'), table_name='synonyms')
    op.drop_table('synonyms')
    op.drop_index(op.f('ix_business_rules_tenant_id'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_semantic_model_version_id'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_entity_id'), table_name='business_rules')
    op.drop_table('business_rules')
    op.drop_index(op.f('ix_glossary_terms_tenant_id'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_semantic_model_version_id'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    # ### end Alembic commands ###
