"""add hybrid search index and full text

Revision ID: b4c68ade9650
Revises: bf8465639689
Create Date: 2026-09-03 03:00:38.622664

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

RLS_TABLES = ("semantic_search_index",)
RLS_POLICY = "tenant_isolation"
RLS_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
# Alembic renders pgvector column types fully qualified without importing them.
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = 'b4c68ade9650'
down_revision: str | None = 'bf8465639689'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_search_index',
    sa.Column('semantic_model_version_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.Enum('entity', 'dimension', 'metric', 'glossary_term', name='search_object_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', search_text)", persisted=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(embedding IS NULL) = (embedding_model IS NULL)', name=op.f('ck_semantic_search_index_embedding_has_model')),
    sa.CheckConstraint('length(trim(search_text)) > 0', name=op.f('ck_semantic_search_index_search_text_present')),
    sa.ForeignKeyConstraint(['semantic_model_version_id', 'tenant_id'], ['semantic_model_versions.id', 'semantic_model_versions.tenant_id'], name='fk_semantic_search_index_semantic_model_version_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_search_index')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_semantic_search_index_id_tenant_id'),
    sa.UniqueConstraint('semantic_model_version_id', 'object_type', 'object_id', name='uq_semantic_search_index_object')
    )
    op.create_index('ix_semantic_search_index_embedding', 'semantic_search_index', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_semantic_search_index_fts', 'semantic_search_index', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_semantic_search_index_name'), 'semantic_search_index', ['name'], unique=False)
    op.create_index(op.f('ix_semantic_search_index_object_id'), 'semantic_search_index', ['object_id'], unique=False)
    op.create_index(op.f('ix_semantic_search_index_semantic_model_version_id'), 'semantic_search_index', ['semantic_model_version_id'], unique=False)
    op.create_index(op.f('ix_semantic_search_index_tenant_id'), 'semantic_search_index', ['tenant_id'], unique=False)
    op.add_column('document_chunks', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False))
    op.create_index('ix_document_chunks_fts', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {RLS_POLICY} ON {table} "
            f"USING ({RLS_PREDICATE}) "
            f"WITH CHECK ({RLS_PREDICATE})"
        )


def downgrade() -> None:
    for table in reversed(RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS {RLS_POLICY} ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_fts', table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'search_vector')
    op.drop_index(op.f('ix_semantic_search_index_tenant_id'), table_name='semantic_search_index')
    op.drop_index(op.f('ix_semantic_search_index_semantic_model_version_id'), table_name='semantic_search_index')
    op.drop_index(op.f('ix_semantic_search_index_object_id'), table_name='semantic_search_index')
    op.drop_index(op.f('ix_semantic_search_index_name'), table_name='semantic_search_index')
    op.drop_index('ix_semantic_search_index_fts', table_name='semantic_search_index', postgresql_using='gin')
    op.drop_index('ix_semantic_search_index_embedding', table_name='semantic_search_index', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('semantic_search_index')
    # ### end Alembic commands ###
