"""add semantic models and versions

Revision ID: bbc8ba79661c
Revises: aec70d6a516d
Create Date: 2026-09-02 17:14:29.950057

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Same predicate as the Step 14 migration. Every tenant-scoped table gets an
# identical copy, so the whole set can be audited by reading rather than parsing.
RLS_TABLES = ("semantic_models", "semantic_model_versions")
RLS_POLICY = "tenant_isolation"
RLS_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"


revision: str = 'bbc8ba79661c'
down_revision: str | None = 'aec70d6a516d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_models',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'tenant_id'], ['workspaces.id', 'workspaces.tenant_id'], name='fk_semantic_models_workspace_id_workspaces', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_models')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_semantic_models_id_tenant_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_semantic_models_workspace_id_name')
    )
    op.create_index(op.f('ix_semantic_models_tenant_id'), 'semantic_models', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_semantic_models_workspace_id'), 'semantic_models', ['workspace_id'], unique=False)
    op.create_table('semantic_model_versions',
    sa.Column('semantic_model_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='version_status', native_enum=False, create_constraint=True, length=32), server_default='draft', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semantic_model_id', 'tenant_id'], ['semantic_models.id', 'semantic_models.tenant_id'], name='fk_semantic_model_versions_semantic_model_id_semantic_models', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_model_versions')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_semantic_model_versions_id_tenant_id'),
    sa.UniqueConstraint('semantic_model_id', 'version', name='uq_semantic_model_versions_semantic_model_id_version')
    )
    op.create_index(op.f('ix_semantic_model_versions_semantic_model_id'), 'semantic_model_versions', ['semantic_model_id'], unique=False)
    op.create_index(op.f('ix_semantic_model_versions_tenant_id'), 'semantic_model_versions', ['tenant_id'], unique=False)
    op.create_index('uq_semantic_model_versions_one_published', 'semantic_model_versions', ['semantic_model_id', 'tenant_id'], unique=True, postgresql_where=sa.text("status = 'published'"))
    # ### end Alembic commands ###

    # Hand-added: Alembic cannot autogenerate policies, and a tenant-scoped
    # table without one is readable by every tenant.
    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {RLS_POLICY} ON {table} "
            f"USING ({RLS_PREDICATE}) "
            f"WITH CHECK ({RLS_PREDICATE})"
        )


def downgrade() -> None:
    for table in reversed(RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS {RLS_POLICY} ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_semantic_model_versions_one_published', table_name='semantic_model_versions', postgresql_where=sa.text("status = 'published'"))
    op.drop_index(op.f('ix_semantic_model_versions_tenant_id'), table_name='semantic_model_versions')
    op.drop_index(op.f('ix_semantic_model_versions_semantic_model_id'), table_name='semantic_model_versions')
    op.drop_table('semantic_model_versions')
    op.drop_index(op.f('ix_semantic_models_workspace_id'), table_name='semantic_models')
    op.drop_index(op.f('ix_semantic_models_tenant_id'), table_name='semantic_models')
    op.drop_table('semantic_models')
    # ### end Alembic commands ###
