"""add chunk embeddings and hnsw index

Revision ID: bf8465639689
Revises: 5fdc26fe2156
Create Date: 2026-09-03 01:10:49.795131

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# autogenerate renders pgvector types fully qualified but does not import them.
import pgvector.sqlalchemy


revision: str = 'bf8465639689'
down_revision: str | None = '5fdc26fe2156'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###

    # Hand-added: Alembic does not detect CHECK constraints on an existing table.
    op.create_check_constraint(
        "embedding_has_model",
        "document_chunks",
        "(embedding IS NULL) = (embedding_model IS NULL)",
    )


def downgrade() -> None:
    # Bare name, not the full one: drop_constraint applies the ck_ naming
    # convention exactly as create_check_constraint does, so passing the full
    # name produces ck_document_chunks_ck_document_chunks_embedding_has_model.
    op.drop_constraint("embedding_has_model", "document_chunks", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('document_chunks', 'embedding_model')
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
